from __future__ import annotations

from typing import Protocol


class KeyStore(Protocol):
    def load_key_pair(self, aid: str) -> dict | None: ...

    def save_key_pair(self, aid: str, key_pair: dict) -> None: ...

    def load_cert(self, aid: str) -> str | None: ...

    def save_cert(self, aid: str, cert_pem: str) -> None: ...

    def load_metadata(self, aid: str) -> dict | None: ...

    def save_metadata(self, aid: str, metadata: dict) -> None: ...

    def delete_key_pair(self, aid: str) -> None: ...

    def load_identity(self, aid: str) -> dict | None: ...

    def save_identity(self, aid: str, identity: dict) -> None: ...

    def delete_identity(self, aid: str) -> None: ...
