export type EventCatalogFieldType = 'string' | 'number' | 'boolean' | 'object' | 'array' | 'unknown';

export interface EventCatalogField {
  path: string;
  type: EventCatalogFieldType;
  optional?: boolean;
  description?: string;
}

export interface EventCatalogEntry {
  type: string;
  namespace: string;
  name: string;
  description: string;
  fields: EventCatalogField[];
  internal?: boolean;
}

const CATALOG: EventCatalogEntry[] = [
  {
    type: 'system:started',
    namespace: 'system',
    name: 'started',
    description: '系统启动完成',
    fields: [
      { path: 'channels', type: 'array' },
      { path: 'timestamp', type: 'number' },
    ],
  },
  {
    type: 'system:shutdown',
    namespace: 'system',
    name: 'shutdown',
    description: '系统关闭',
    fields: [
      { path: 'reason', type: 'string', optional: true },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'system:restart',
    namespace: 'system',
    name: 'restart',
    description: '当前运行时请求重启',
    fields: [
      { path: 'channel', type: 'string' },
      { path: 'channelId', type: 'string' },
    ],
  },
  {
    type: 'channel:connected',
    namespace: 'channel',
    name: 'connected',
    description: '渠道连接成功',
    fields: [
      { path: 'channel', type: 'string' },
      { path: 'channelName', type: 'string', optional: true },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'channel:disconnected',
    namespace: 'channel',
    name: 'disconnected',
    description: '渠道断开',
    fields: [
      { path: 'channel', type: 'string' },
      { path: 'channelName', type: 'string', optional: true },
      { path: 'reason', type: 'string', optional: true },
    ],
  },
  {
    type: 'channel:error',
    namespace: 'channel',
    name: 'error',
    description: '渠道错误',
    fields: [
      { path: 'channel', type: 'string' },
      { path: 'channelName', type: 'string', optional: true },
      { path: 'status', type: 'string' },
      { path: 'message', type: 'string' },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'channel:owner-bound',
    namespace: 'channel',
    name: 'owner-bound',
    description: '渠道 owner 绑定',
    fields: [
      { path: 'channel', type: 'string' },
      { path: 'channelName', type: 'string', optional: true },
      { path: 'userId', type: 'string' },
    ],
  },
  {
    type: 'session:created',
    namespace: 'session',
    name: 'created',
    description: '会话创建',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'channel', type: 'string' },
      { path: 'channelName', type: 'string', optional: true },
      { path: 'channelId', type: 'string' },
      { path: 'projectPath', type: 'string', optional: true },
      { path: 'name', type: 'string', optional: true },
      { path: 'chatType', type: 'string', optional: true },
      { path: 'threadId', type: 'string', optional: true },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'session:switched',
    namespace: 'session',
    name: 'switched',
    description: '会话切换',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'fromSessionId', type: 'string' },
      { path: 'toSessionId', type: 'string' },
    ],
  },
  {
    type: 'session:deleted',
    namespace: 'session',
    name: 'deleted',
    description: '会话删除',
    fields: [{ path: 'sessionId', type: 'string' }],
  },
  {
    type: 'session:renamed',
    namespace: 'session',
    name: 'renamed',
    description: '会话重命名',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'oldName', type: 'string' },
      { path: 'newName', type: 'string' },
    ],
  },
  {
    type: 'session:forked',
    namespace: 'session',
    name: 'forked',
    description: '会话 fork',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'sourceSessionId', type: 'string' },
      { path: 'name', type: 'string', optional: true },
    ],
  },
  {
    type: 'session:rewind',
    namespace: 'session',
    name: 'rewind',
    description: '会话回退',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'turnNum', type: 'number' },
      { path: 'mode', type: 'string' },
    ],
  },
  {
    type: 'session:imported',
    namespace: 'session',
    name: 'imported',
    description: '导入 agent 会话',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'agentSessionId', type: 'string' },
      { path: 'projectPath', type: 'string' },
    ],
  },
  {
    type: 'session:chat-mode-changed',
    namespace: 'session',
    name: 'chat-mode-changed',
    description: 'chat mode 修改',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'mode', type: 'string' },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'session:dispatch-mode-changed',
    namespace: 'session',
    name: 'dispatch-mode-changed',
    description: 'dispatch mode 修改',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'mode', type: 'string' },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'message:received',
    namespace: 'message',
    name: 'received',
    description: '消息到达',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'channel', type: 'string' },
      { path: 'channelName', type: 'string', optional: true },
      { path: 'channelId', type: 'string' },
      { path: 'content', type: 'string' },
      { path: 'userId', type: 'string', optional: true },
      { path: 'agentName', type: 'string', optional: true },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'message:sent',
    namespace: 'message',
    name: 'sent',
    description: '消息发送',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'channel', type: 'string' },
      { path: 'channelName', type: 'string', optional: true },
      { path: 'channelId', type: 'string' },
      { path: 'agentName', type: 'string', optional: true },
      { path: 'payloadKind', type: 'string', optional: true },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'message:text',
    namespace: 'message',
    name: 'text',
    description: 'agent 文本流输出',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'text', type: 'string' },
      { path: 'isFinal', type: 'boolean' },
    ],
  },
  {
    type: 'message:thought-put',
    namespace: 'message',
    name: 'thought-put',
    description: 'agent thought/progress 输出',
    fields: [
      { path: 'agentName', type: 'string' },
      { path: 'channelId', type: 'string' },
      { path: 'taskId', type: 'string', optional: true },
      { path: 'text', type: 'string', optional: true },
    ],
  },
  {
    type: 'task:started',
    namespace: 'task',
    name: 'started',
    description: 'agent 任务开始',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'agentName', type: 'string', optional: true },
      { path: 'encrypt', type: 'boolean', optional: true },
      { path: 'chatmode', type: 'string', optional: true },
    ],
  },
  {
    type: 'task:queued',
    namespace: 'task',
    name: 'queued',
    description: '任务入队',
    fields: [
      { path: 'channel', type: 'string' },
      { path: 'channelId', type: 'string' },
      { path: 'replyContext', type: 'object', optional: true },
    ],
  },
  {
    type: 'task:completed',
    namespace: 'task',
    name: 'completed',
    description: 'agent 任务完成',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'channel', type: 'string' },
      { path: 'channelName', type: 'string', optional: true },
      { path: 'channelId', type: 'string' },
      { path: 'finalText', type: 'string', optional: true },
      { path: 'durationMs', type: 'number', optional: true },
      { path: 'terminalReason', type: 'string', optional: true },
      { path: 'agentName', type: 'string', optional: true },
      { path: 'numTurns', type: 'number', optional: true },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'task:error',
    namespace: 'task',
    name: 'error',
    description: 'agent 任务失败',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'error', type: 'string' },
      { path: 'errorType', type: 'string' },
      { path: 'terminalReason', type: 'string', optional: true },
      { path: 'agentName', type: 'string', optional: true },
    ],
  },
  {
    type: 'task:interrupted',
    namespace: 'task',
    name: 'interrupted',
    description: 'agent 任务被中断',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'reason', type: 'string', optional: true },
      { path: 'agentName', type: 'string', optional: true },
    ],
  },
  {
    type: 'tool:use',
    namespace: 'tool',
    name: 'use',
    description: '工具调用开始',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'toolName', type: 'string' },
      { path: 'input', type: 'object' },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'tool:result',
    namespace: 'tool',
    name: 'result',
    description: '工具调用结束',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'toolName', type: 'string' },
      { path: 'isError', type: 'boolean', optional: true },
      { path: 'agentName', type: 'string', optional: true },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'permission:requested',
    namespace: 'permission',
    name: 'requested',
    description: '权限请求创建',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'requestId', type: 'string' },
      { path: 'toolName', type: 'string' },
      { path: 'input', type: 'string' },
    ],
  },
  {
    type: 'permission:resolved',
    namespace: 'permission',
    name: 'resolved',
    description: '权限请求被批准或拒绝',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'requestId', type: 'string' },
      { path: 'approved', type: 'boolean' },
    ],
  },
  {
    type: 'permission:cancelled',
    namespace: 'permission',
    name: 'cancelled',
    description: 'pending 权限请求被取消',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'requestId', type: 'string' },
      { path: 'toolName', type: 'string', optional: true },
      { path: 'reason', type: 'string', optional: true },
    ],
  },
  {
    type: 'runner:compact-start',
    namespace: 'runner',
    name: 'compact-start',
    description: 'runner 开始压缩',
    fields: [{ path: 'sessionId', type: 'string' }],
  },
  {
    type: 'runner:compact-complete',
    namespace: 'runner',
    name: 'compact-complete',
    description: 'runner 压缩完成',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'preTokens', type: 'number' },
    ],
  },
  {
    type: 'runner:model-changed',
    namespace: 'runner',
    name: 'model-changed',
    description: '模型或推理强度修改',
    fields: [
      { path: 'sessionId', type: 'string', optional: true },
      { path: 'agentName', type: 'string', optional: true },
      { path: 'baseagent', type: 'string', optional: true },
      { path: 'model', type: 'string', optional: true },
      { path: 'effort', type: 'string', optional: true },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'runner:idle-timeout',
    namespace: 'runner',
    name: 'idle-timeout',
    description: 'runner 空闲超时',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'idleSec', type: 'number' },
    ],
  },
  {
    type: 'runner:idle-notify',
    namespace: 'runner',
    name: 'idle-notify',
    description: 'runner 空闲提醒',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'idleSec', type: 'number' },
      { path: 'totalEvents', type: 'number' },
      { path: 'totalToolCalls', type: 'number' },
      { path: 'lastToolName', type: 'string', optional: true },
    ],
  },
  {
    type: 'runner:idle-warn',
    namespace: 'runner',
    name: 'idle-warn',
    description: 'runner 空闲警告',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'idleSec', type: 'number' },
      { path: 'totalEvents', type: 'number' },
      { path: 'totalToolCalls', type: 'number' },
      { path: 'lastToolName', type: 'string', optional: true },
    ],
  },
  {
    type: 'runner:file-sent',
    namespace: 'runner',
    name: 'file-sent',
    description: '文件发送完成',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'filePath', type: 'string' },
      { path: 'channel', type: 'string' },
      { path: 'channelName', type: 'string', optional: true },
    ],
  },
  {
    type: 'runner:state-changed',
    namespace: 'runner',
    name: 'state-changed',
    description: 'runner 状态变化',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'state', type: 'string' },
    ],
  },
  {
    type: 'runner:status',
    namespace: 'runner',
    name: 'status',
    description: 'runner 状态消息',
    fields: [
      { path: 'sessionId', type: 'string' },
      { path: 'subtype', type: 'string' },
      { path: 'message', type: 'string' },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'self-heal:started',
    namespace: 'self-heal',
    name: 'started',
    description: '自愈流程开始',
    fields: [{ path: 'reason', type: 'string' }],
  },
  {
    type: 'self-heal:attempt',
    namespace: 'self-heal',
    name: 'attempt',
    description: '自愈尝试',
    fields: [
      { path: 'attemptNumber', type: 'number' },
      { path: 'maxAttempts', type: 'number' },
    ],
  },
  {
    type: 'self-heal:completed',
    namespace: 'self-heal',
    name: 'completed',
    description: '自愈完成',
    fields: [
      { path: 'success', type: 'boolean' },
      { path: 'attempts', type: 'number' },
    ],
  },
  {
    type: 'trigger:registered',
    namespace: 'trigger',
    name: 'registered',
    description: 'trigger 创建',
    internal: true,
    fields: [
      { path: 'triggerId', type: 'string' },
      { path: 'name', type: 'string' },
      { path: 'peerId', type: 'string', optional: true },
      { path: 'targetChannel', type: 'string', optional: true },
      { path: 'targetChannelId', type: 'string', optional: true },
      { path: 'scheduleType', type: 'string' },
      { path: 'scheduleValue', type: 'string' },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'trigger:updated',
    namespace: 'trigger',
    name: 'updated',
    description: 'trigger 更新',
    internal: true,
    fields: [
      { path: 'triggerId', type: 'string' },
      { path: 'name', type: 'string' },
      { path: 'peerId', type: 'string', optional: true },
      { path: 'scheduleType', type: 'string' },
      { path: 'scheduleValue', type: 'string' },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'trigger:fired',
    namespace: 'trigger',
    name: 'fired',
    description: 'trigger run 开始',
    internal: true,
    fields: [
      { path: 'triggerId', type: 'string' },
      { path: 'name', type: 'string' },
      { path: 'runId', type: 'string' },
      { path: 'originTriggerId', type: 'string' },
      { path: 'fireTime', type: 'number' },
      { path: 'targetChannel', type: 'string', optional: true },
      { path: 'targetChannelId', type: 'string', optional: true },
      { path: 'scheduleType', type: 'string' },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'trigger:completed',
    namespace: 'trigger',
    name: 'completed',
    description: 'trigger run 完成',
    internal: true,
    fields: [
      { path: 'triggerId', type: 'string' },
      { path: 'name', type: 'string' },
      { path: 'runId', type: 'string' },
      { path: 'originTriggerId', type: 'string' },
      { path: 'messageId', type: 'string' },
      { path: 'durationMs', type: 'number' },
      { path: 'targetChannel', type: 'string' },
      { path: 'targetChannelId', type: 'string' },
      { path: 'fireTime', type: 'number' },
    ],
  },
  {
    type: 'trigger:failed',
    namespace: 'trigger',
    name: 'failed',
    description: 'trigger run 失败',
    internal: true,
    fields: [
      { path: 'triggerId', type: 'string' },
      { path: 'name', type: 'string' },
      { path: 'runId', type: 'string' },
      { path: 'originTriggerId', type: 'string' },
      { path: 'messageId', type: 'string' },
      { path: 'error', type: 'string' },
      { path: 'targetChannel', type: 'string' },
      { path: 'targetChannelId', type: 'string' },
      { path: 'fireTime', type: 'number' },
      { path: 'phase', type: 'string' },
    ],
  },
  {
    type: 'trigger:skipped',
    namespace: 'trigger',
    name: 'skipped',
    description: 'trigger run 跳过',
    internal: true,
    fields: [
      { path: 'triggerId', type: 'string' },
      { path: 'name', type: 'string' },
      { path: 'runId', type: 'string' },
      { path: 'originTriggerId', type: 'string' },
      { path: 'reason', type: 'string' },
      { path: 'targetChannel', type: 'string' },
      { path: 'targetChannelId', type: 'string' },
      { path: 'fireTime', type: 'number', optional: true },
    ],
  },
  {
    type: 'trigger:cancelled',
    namespace: 'trigger',
    name: 'cancelled',
    description: 'trigger 被取消',
    internal: true,
    fields: [
      { path: 'triggerId', type: 'string' },
      { path: 'name', type: 'string' },
      { path: 'by', type: 'string' },
    ],
  },
  {
    type: 'agent:created',
    namespace: 'agent',
    name: 'created',
    description: 'agent 创建',
    fields: [
      { path: 'aid', type: 'string' },
      { path: 'name', type: 'string', optional: true },
      { path: 'baseagent', type: 'string', optional: true },
      { path: 'projectPath', type: 'string', optional: true },
      { path: 'owner', type: 'string', optional: true },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'agent:bootstrap-started',
    namespace: 'agent',
    name: 'bootstrap-started',
    description: 'agent bootstrap 开始',
    fields: [
      { path: 'aid', type: 'string' },
      { path: 'channel', type: 'string', optional: true },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'agent:bootstrap-complete',
    namespace: 'agent',
    name: 'bootstrap-complete',
    description: 'agent bootstrap 完成',
    fields: [
      { path: 'aid', type: 'string' },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'agent:updated',
    namespace: 'agent',
    name: 'updated',
    description: 'agent 配置更新',
    fields: [
      { path: 'aid', type: 'string' },
      { path: 'nameChanged', type: 'boolean', optional: true },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'agent:avatar_updated',
    namespace: 'agent',
    name: 'avatar_updated',
    description: 'agent 头像更新',
    fields: [
      { path: 'aid', type: 'string' },
      { path: 'avatar', type: 'string' },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'agent:reloaded',
    namespace: 'agent',
    name: 'reloaded',
    description: 'agent 重载',
    fields: [
      { path: 'aid', type: 'string' },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'agent:enabled',
    namespace: 'agent',
    name: 'enabled',
    description: 'agent 启用',
    fields: [
      { path: 'aid', type: 'string' },
      { path: 'reloaded', type: 'boolean', optional: true },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'agent:disabled',
    namespace: 'agent',
    name: 'disabled',
    description: 'agent 禁用',
    fields: [
      { path: 'aid', type: 'string' },
      { path: 'reloaded', type: 'boolean', optional: true },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'agent:deleted',
    namespace: 'agent',
    name: 'deleted',
    description: 'agent 删除',
    fields: [
      { path: 'aid', type: 'string' },
      { path: 'purged', type: 'boolean', optional: true },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'agent:started',
    namespace: 'agent',
    name: 'started',
    description: 'agent 运行态启动',
    fields: [
      { path: 'aid', type: 'string' },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'agent:stopped',
    namespace: 'agent',
    name: 'stopped',
    description: 'agent 运行态停止',
    fields: [
      { path: 'aid', type: 'string' },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'agent:error',
    namespace: 'agent',
    name: 'error',
    description: 'agent 操作失败',
    fields: [
      { path: 'aid', type: 'string' },
      { path: 'action', type: 'string', optional: true },
      { path: 'error', type: 'string' },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
  {
    type: 'agent:baseagent-changed',
    namespace: 'agent',
    name: 'baseagent-changed',
    description: 'agent 默认 baseagent 修改',
    fields: [
      { path: 'aid', type: 'string' },
      { path: 'baseagent', type: 'string' },
      { path: 'previousBaseagent', type: 'string', optional: true },
      { path: 'scope', type: 'string' },
      { path: 'timestamp', type: 'number', optional: true },
    ],
  },
];

export function getEventCatalog(opts: { includeInternal?: boolean } = {}): {
  namespaces: string[];
  events: EventCatalogEntry[];
} {
  const events = CATALOG
    .filter(entry => opts.includeInternal || !entry.internal)
    .map(entry => ({
      ...entry,
      fields: entry.fields.map(field => ({ ...field })),
    }));
  const namespaces = [...new Set(events.map(entry => entry.namespace))].sort();
  return { namespaces, events };
}
